# Generated by Django 6.0.2 on 2026-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_is_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT', 'Tarjeta de Débito / Cuenta de Banco'), ('CREDIT', 'Tarjeta de Crédito'), ('SAVINGS', 'Cuenta de Ahorro / Inversión')], max_length=10),
        ),
    ]
