# Generated by Django 6.0.2 on 2026-05-28 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Credit card payment due day (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='account',
            name='statement_cut_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Credit card statement cut day (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
