# Generated by Codex on 2026-06-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_account_credit_limit_account_payment_due_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spending_kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NECESSARY', 'Necesario'),
                    ('OUTING', 'Salida'),
                    ('IMPULSE', 'Impulsivo'),
                    ('OPTIONAL', 'Opcional'),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emergency_fund_goal', models.DecimalField(decimal_places=2, default=30000.0, max_digits=12)),
                ('monthly_outing_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('weekly_work_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_goal', models.CharField(default='Eliminar deudas', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
