# Generated by Codex on 2026-07-07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('goal', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Completado')], default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='life_studen_user_id_51f562_idx'),
                    models.Index(fields=['user', 'next_follow_up'], name='life_studen_user_id_b2d921_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('company_focus', models.TextField(blank=True)),
                ('skills_focus', models.TextField(blank=True)),
                ('personal_focus', models.TextField(blank=True)),
                ('health_focus', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_focuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [
                    models.Index(fields=['user', 'year', 'month'], name='life_monthl_user_id_b94e5a_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_monthly_focus_per_user_month'),
                ],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('WORK', 'Trabajo'), ('BUSINESS', 'Empresa'), ('PERSONAL', 'Personal'), ('CLASS', 'Clases')], default='WORK', max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Hecho'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes', models.PositiveSmallIntegerField(default=1440)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='life_workta_user_id_be1118_idx'),
                    models.Index(fields=['user', 'due_at'], name='life_workta_user_id_39bae2_idx'),
                    models.Index(fields=['user', 'area'], name='life_workta_user_id_8f0787_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=20)),
                ('event_key', models.CharField(max_length=180)),
                ('event_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [
                    models.Index(fields=['user', 'channel', 'event_date'], name='life_notifi_user_id_e8d240_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'channel', 'event_key', 'event_date'), name='unique_life_notification_event'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('topic', models.CharField(max_length=180)),
                ('homework', models.TextField(blank=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='SCHEDULED', max_length=12)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes', models.PositiveSmallIntegerField(default=60)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='life.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [
                    models.Index(fields=['user', 'scheduled_at'], name='life_lesson_user_id_3dbc02_idx'),
                    models.Index(fields=['user', 'status'], name='life_lesson_user_id_3e2215_idx'),
                ],
            },
        ),
    ]
